import ReweightedNPMLE.GaussianSampling
import ReweightedNPMLE.ProbabilityOptimizerFiber
import Mathlib.Tactic

/-! # The literal simultaneous finite-net lemma

The same deterministic moment and rounding grids used for the near-MLE bound
give the stronger inverse-cubic Hellinger and uniform log-density errors.
Every grid density is generated by a probability law on the original compact
location set, and the radius tail is uniform over the generating law.
-/

open Set Filter MeasureTheory
open scoped Topology BigOperators ENNReal

namespace ReweightedNPMLE

private theorem inv_natpow_le {x : ℝ} (hx : 1 ≤ x) {i j : ℕ} (hij : i ≤ j) :
    1 / x ^ j ≤ 1 / x ^ i :=
  div_le_div_of_nonneg_left (by norm_num) (by positivity)
    (pow_le_pow_right₀ hx hij)

theorem eventually_gaussianMomentHellingerError_256_le_inv_pow12
    {S : ℝ} (hS : 0 ≤ S) :
    ∀ᶠ n : ℕ in atTop,
      gaussianMomentHellingerError S (gaussianPaperMomentOrder 256 n) ≤
        1 / (n : ℝ) ^ 12 := by
  let A := 4 * Real.exp (S ^ 2)
  filter_upwards [eventually_gaussianMomentHellingerError_paper_le
      (show (0 : ℝ) < 256 by norm_num) hS,
    tendsto_natCast_atTop_atTop.eventually_ge_atTop A,
    Filter.eventually_ge_atTop (1 : ℕ)] with n hglobal hAn hn
  have hnreal : (0 : ℝ) < n := by exact_mod_cast (show 0 < n by omega)
  have hnOne : (1 : ℝ) ≤ n := by exact_mod_cast hn
  have hA8 : A ≤ (n : ℝ) ^ 8 := by
    calc
      A ≤ (n : ℝ) := hAn
      _ = (n : ℝ) ^ 1 := by ring
      _ ≤ (n : ℝ) ^ 8 := pow_le_pow_right₀ hnOne (by omega)
  have hneg : (n : ℝ) ^ (-256 / 8 : ℝ) = 1 / (n : ℝ) ^ 32 := by
    norm_num [Real.rpow_neg_natCast, zpow_neg, div_eq_mul_inv]
    rfl
  have hinside : A * (n : ℝ) ^ (-256 / 8 : ℝ) ≤ 1 / (n : ℝ) ^ 24 := by
    rw [hneg]
    calc
      A * (1 / (n : ℝ) ^ 32) ≤ (n : ℝ) ^ 8 * (1 / (n : ℝ) ^ 32) := by
        gcongr
      _ = 1 / (n : ℝ) ^ 24 := by field_simp
  calc
    gaussianMomentHellingerError S (gaussianPaperMomentOrder 256 n) ≤
        (A * (n : ℝ) ^ (-256 / 8 : ℝ)) ^ (1 / 2 : ℝ) := by
      simpa only [A] using hglobal
    _ ≤ (1 / (n : ℝ) ^ 24) ^ (1 / 2 : ℝ) :=
      Real.rpow_le_rpow (by dsimp [A]; positivity) hinside (by norm_num)
    _ = 1 / (n : ℝ) ^ 12 := by
      rw [← Real.sqrt_eq_rpow]
      have hsquare : 1 / (n : ℝ) ^ 24 = (1 / (n : ℝ) ^ 12) ^ 2 := by
        field_simp
      rw [hsquare, Real.sqrt_sq (by positivity)]

theorem eventually_gaussianNetHellingerSqError_256_le_inv_pow6
    (d : ℕ) {S : ℝ} (hS : 0 ≤ S) :
    ∀ᶠ n : ℕ in atTop,
      gaussianNetHellingerSqError d (gaussianPaperMomentOrder 256 n)
        (gaussianPaperWeightDenominator d 256 n) S (gaussianPaperEpsilon n) ≤
          1 / (n : ℝ) ^ 6 := by
  filter_upwards [eventually_gaussianMomentHellingerError_256_le_inv_pow12 hS,
    Filter.eventually_ge_atTop (3 : ℕ)] with n hglobal hn
  have hnpos : 0 < n := by omega
  have hnreal : (0 : ℝ) < n := by exact_mod_cast hnpos
  have hnThree : (3 : ℝ) ≤ n := by exact_mod_cast hn
  have hnOne : (1 : ℝ) ≤ n := by linarith
  have hround := gaussianPaper_weight_rounding_le d (256 : ℝ) hnpos
  have heps : gaussianPaperEpsilon n ^ 2 ≤ 1 / (n : ℝ) ^ 12 := by
    have heq : gaussianPaperEpsilon n ^ 2 = 1 / (n : ℝ) ^ 32 := by
      unfold gaussianPaperEpsilon
      field_simp
    rw [heq]
    exact inv_natpow_le hnOne (by omega)
  have hround' :
      4 * (2 * gaussianMomentDimension d (gaussianPaperMomentOrder 256 n) /
        gaussianPaperWeightDenominator d 256 n) ≤ 8 / (n : ℝ) ^ 12 := by
    calc
      _ ≤ 4 * (2 / (n : ℝ) ^ 16) := by gcongr
      _ = 8 * (1 / (n : ℝ) ^ 16) := by ring
      _ ≤ 8 * (1 / (n : ℝ) ^ 12) := by
        gcongr
        omega
      _ = 8 / (n : ℝ) ^ 12 := by ring
  have herror : gaussianNetHellingerSqError d (gaussianPaperMomentOrder 256 n)
      (gaussianPaperWeightDenominator d 256 n) S (gaussianPaperEpsilon n) ≤
        11 / (n : ℝ) ^ 12 := by
    unfold gaussianNetHellingerSqError
    calc
      _ ≤ 2 * (1 / (n : ℝ) ^ 12) + 1 / (n : ℝ) ^ 12 + 8 / (n : ℝ) ^ 12 :=
        add_le_add (add_le_add (by gcongr) heps) hround'
      _ = 11 / (n : ℝ) ^ 12 := by ring
  apply herror.trans
  have hpow : (11 : ℝ) ≤ (n : ℝ) ^ 6 := by
    calc
      (11 : ℝ) ≤ 3 ^ 6 := by norm_num
      _ ≤ (n : ℝ) ^ 6 := pow_le_pow_left₀ (by norm_num) hnThree _
  rw [div_le_div_iff₀ (pow_pos hnreal 12) (pow_pos hnreal 6)]
  rw [show (n : ℝ) ^ 12 = (n : ℝ) ^ 6 * (n : ℝ) ^ 6 by ring]
  nlinarith [pow_pos hnreal 6]

theorem eventually_gaussianNetLogError_256_le_inv_pow3
    (d : ℕ) {S b : ℝ} (hS : 0 ≤ S) (hb : 0 ≤ b) :
    ∀ᶠ n : ℕ in atTop,
      gaussianNetLogError d (gaussianPaperMomentOrder 256 n)
        (gaussianPaperWeightDenominator d 256 n)
        (gaussianPaperSampleRadius d S b n) S (gaussianPaperEpsilon n) ≤
          1 / (n : ℝ) ^ 3 := by
  filter_upwards [eventually_gaussianPaperSampleRadius_add_le_sq d hS hb,
    eventually_gaussianPaper_weightTerm_le d (C := (256 : ℝ)) hS hb,
    eventually_gaussianMomentRelativeError_256_le d hS hb,
    Filter.eventually_ge_atTop (2 : ℕ)] with n hT hweight hrel hn
  let T := gaussianPaperSampleRadius d S b n
  let L := gaussianPaperMomentOrder 256 n
  let M := gaussianPaperWeightDenominator d 256 n
  have hnreal : (0 : ℝ) < n := by exact_mod_cast (show 0 < n by omega)
  have hnTwo : (2 : ℝ) ≤ n := by exact_mod_cast hn
  have hnOne : (1 : ℝ) ≤ n := by linarith
  have hmesh : (T + S) * gaussianPaperEpsilon n ≤ 1 / (n : ℝ) ^ 14 := by
    unfold gaussianPaperEpsilon
    calc
      _ ≤ (n : ℝ) ^ 2 * ((n : ℝ) ^ 16)⁻¹ := by gcongr
      _ = 1 / (n : ℝ) ^ 14 := by field_simp
  have hweight' : Real.exp (2 * (T * S + S ^ 2 / 2)) *
      (2 * gaussianMomentDimension d L / M) ≤ 2 / (n : ℝ) ^ 15 := by
    simpa only [T, L, M, gaussianPaperTaylorArgument] using hweight
  have hrel' : gaussianMomentRelativeError T S L ≤ 2 / (n : ℝ) ^ 31 := by
    simpa only [T, L] using hrel
  have hδ : gaussianNetLogError d L M T S (gaussianPaperEpsilon n) ≤
      1 / (n : ℝ) ^ 14 + 4 / (n : ℝ) ^ 15 + 4 / (n : ℝ) ^ 31 := by
    unfold gaussianNetLogError
    have hw : 2 * Real.exp (2 * (T * S + S ^ 2 / 2)) *
        (2 * gaussianMomentDimension d L / M) ≤ 4 / (n : ℝ) ^ 15 := by
      convert mul_le_mul_of_nonneg_left hweight' (show (0 : ℝ) ≤ 2 by norm_num) using 1 <;> ring
    have hr : 2 * gaussianMomentRelativeError T S L ≤ 4 / (n : ℝ) ^ 31 := by
      convert mul_le_mul_of_nonneg_left hrel' (show (0 : ℝ) ≤ 2 by norm_num) using 1 <;> ring
    exact add_le_add (add_le_add hmesh hw) hr
  have hδ' : gaussianNetLogError d L M T S (gaussianPaperEpsilon n) ≤
      9 / (n : ℝ) ^ 14 := by
    calc
      _ ≤ 1 / (n : ℝ) ^ 14 + 4 / (n : ℝ) ^ 15 + 4 / (n : ℝ) ^ 31 := hδ
      _ ≤ 1 / (n : ℝ) ^ 14 + 4 * (1 / (n : ℝ) ^ 14) +
          4 * (1 / (n : ℝ) ^ 14) := by
        have h15 := inv_natpow_le hnOne (show 14 ≤ 15 by omega)
        have h31 := inv_natpow_le hnOne (show 14 ≤ 31 by omega)
        convert add_le_add (add_le_add (le_refl (1 / (n : ℝ) ^ 14))
          (mul_le_mul_of_nonneg_left h15 (show (0 : ℝ) ≤ 4 by norm_num)))
          (mul_le_mul_of_nonneg_left h31 (show (0 : ℝ) ≤ 4 by norm_num)) using 1 <;> ring
      _ = 9 / (n : ℝ) ^ 14 := by ring
  apply hδ'.trans
  have hpow : (9 : ℝ) ≤ (n : ℝ) ^ 11 := by
    calc
      (9 : ℝ) ≤ 2 ^ 11 := by norm_num
      _ ≤ (n : ℝ) ^ 11 := pow_le_pow_left₀ (by norm_num) hnTwo _
  rw [div_le_div_iff₀ (pow_pos hnreal 14) (pow_pos hnreal 3)]
  rw [show (n : ℝ) ^ 14 = (n : ℝ) ^ 3 * (n : ℝ) ^ 11 by ring]
  nlinarith [pow_pos hnreal 3]

theorem compactGaussianMixtureDensity_finiteProbabilityMeasure
    {d m : ℕ} {K : Set (Point d)} (hKcompact : IsCompact K)
    (θ : Fin m → K) (v : Fin m → ℝ) (hv : v ∈ finiteSimplex m) :
    compactGaussianMixtureDensity (finiteProbabilityMeasure θ v hv) =
      finiteGaussianMixture v (fun i ↦ (θ i : Point d)) := by
  funext x
  change (∫ a : K, gaussianKernel d x (a : Point d)
    ∂(∑ j, ENNReal.ofReal (v j) • Measure.dirac (θ j))) =
      ∑ j, v j * gaussianKernel d x (θ j : Point d)
  rw [integral_finsetSum_measure]
  · simp only [integral_smul_measure, integral_dirac, ENNReal.toReal_ofReal (hv.1 _),
      smul_eq_mul]
  · intro j _
    exact (integrable_dirac (by simp)).smul_measure ENNReal.ofReal_ne_top

theorem mem_gaussianGrid_is_compactGaussianMixtureDensity
    {d k M : ℕ} {K : Set (Point d)} (hKcompact : IsCompact K)
    (Q : Finset (Point d)) (hQK : (Q : Set (Point d)) ⊆ K)
    {p : Point d → ℝ} (hp : p ∈ finiteGaussianMixtureGrid d k M Q) :
    ∃ G : ProbabilityMeasure K, p = compactGaussianMixtureDensity G := by
  rcases (mem_finiteGaussianMixtureGrid_iff Q).mp hp with ⟨z, v, hv, rfl⟩
  let θ : Fin (k + 1) → K := fun i ↦ ⟨(z i : Point d), hQK (z i).property⟩
  have hvSimplex : v ∈ finiteSimplex (k + 1) :=
    ⟨validSimplexWeightGrid_nonneg hv, validSimplexWeightGrid_sum hv⟩
  refine ⟨finiteProbabilityMeasure θ v hvSimplex, ?_⟩
  rw [compactGaussianMixtureDensity_finiteProbabilityMeasure hKcompact]

theorem eventually_gaussianPaperSampleRadius_le_sqrt_log
    (d : ℕ) {S b : ℝ} (hS : 0 ≤ S) (hb : 0 ≤ b) :
    ∀ᶠ n : ℕ in atTop,
      gaussianPaperSampleRadius d S b n ≤
        (S + Real.sqrt (d : ℝ) * Real.sqrt (2 * (b + 4))) * Real.sqrt (Real.log n) := by
  have hlog : Tendsto (fun n : ℕ ↦ Real.log (n : ℝ)) atTop atTop :=
    Real.tendsto_log_atTop.comp tendsto_natCast_atTop_atTop
  filter_upwards [hlog.eventually_ge_atTop 1] with n hn
  have hsqrtlog : 1 ≤ Real.sqrt (Real.log (n : ℝ)) := by
    simpa only [Real.sqrt_one] using Real.sqrt_le_sqrt hn
  unfold gaussianPaperSampleRadius gaussianPaperRadiusExponent
  rw [show 2 * ((b + 4) * Real.log (n : ℝ)) =
      (2 * (b + 4)) * Real.log (n : ℝ) by ring,
    Real.sqrt_mul (by positivity : 0 ≤ 2 * (b + 4))]
  nlinarith

theorem compactGaussianSampleMeasure_strengthened_paper_radius_tail
    {d n : ℕ} {K : Set (Point d)} (Gstar : ProbabilityMeasure K)
    {S b : ℝ} (hS : 0 ≤ S) (hb : 0 ≤ b)
    (hKbound : ∀ a ∈ K, ‖a‖ ≤ S) (hlog : 0 < Real.log (n : ℝ))
    (hn : 1 ≤ n) (hdn : 2 * (d : ℝ) + 1 ≤ n) :
    (compactGaussianSampleMeasure Gstar n).real
      {x | ∃ i, gaussianPaperSampleRadius d S (b + 1) n < ‖x i‖} ≤
        (n : ℝ) ^ (-(b + 2)) := by
  have hnreal : (0 : ℝ) < n := by exact_mod_cast (show 0 < n by omega)
  have htail := compactGaussianSampleMeasure_paper_radius_tail Gstar hS
    (show 0 ≤ b + 1 by linarith) hKbound hlog hn
  apply htail.trans
  rw [show -(b + 1 + 2) = -(b + 2) + (-1 : ℝ) by ring,
    Real.rpow_add hnreal, Real.rpow_neg_one]
  calc
    (2 * (d : ℝ) + 1) * ((n : ℝ) ^ (-(b + 2)) * (n : ℝ)⁻¹) =
        ((2 * (d : ℝ) + 1) / n) * (n : ℝ) ^ (-(b + 2)) := by ring
    _ ≤ 1 * (n : ℝ) ^ (-(b + 2)) :=
      mul_le_mul_of_nonneg_right ((div_le_one hnreal).mpr hdn) (Real.rpow_nonneg hnreal.le _)
    _ = (n : ℝ) ^ (-(b + 2)) := one_mul _

/-- Lemma `lem:finite-net`, including the literal displayed entropy order,
inverse-cubic Hellinger/log errors and uniform radius failure without a
multiplicative prefactor. The net and radius are chosen before either law. -/
theorem compactGaussianMixture_simultaneous_paper_finite_net
    {d : ℕ} (K : Set (Point d)) (hKcompact : IsCompact K) (hKnonempty : K.Nonempty)
    {S b : ℝ} (hS : 0 ≤ S) (hb : 0 < b) (hKbound : ∀ u ∈ K, ‖u‖ ≤ S) :
    ∃ C : ℝ, 0 < C ∧ ∀ᶠ n : ℕ in atTop,
      ∃ (N : Finset (Point d → ℝ)) (T : ℝ), N.Nonempty ∧ 0 ≤ T ∧
        T ≤ C * Real.sqrt (Real.log n) ∧
        Real.log (N.card : ℝ) ≤
          C * Real.log (n : ℝ) ^ (d + 1) / Real.log (Real.log (n : ℝ)) ^ d ∧
        (∀ p ∈ N, ∃ G : ProbabilityMeasure K, p = compactGaussianMixtureDensity G) ∧
        (∀ Gstar : ProbabilityMeasure K,
          (compactGaussianSampleMeasure Gstar n).real {x | ∃ i, T < ‖x i‖} ≤
            (n : ℝ) ^ (-(b + 2))) ∧
        ∀ G : ProbabilityMeasure K, ∃ p ∈ N,
          Real.sqrt (hellingerSq volume p (compactGaussianMixtureDensity G)) ≤
            1 / (n : ℝ) ^ 3 ∧
          ∀ y : Point d, ‖y‖ ≤ T →
            |Real.log (p y) - Real.log (compactGaussianMixtureDensity G y)| ≤
              1 / (n : ℝ) ^ 3 := by
  classical
  let β := b + 1
  have hβ : 0 ≤ β := by dsimp [β]; linarith
  let E := gaussianPaperEntropyConstant d
  let R := S + Real.sqrt (d : ℝ) * Real.sqrt (2 * (β + 4))
  let C := 1 + E + R
  have hE : 0 ≤ E := by dsimp [E, gaussianPaperEntropyConstant]; positivity
  have hR : 0 ≤ R := by dsimp [R]; positivity
  have hC : 0 < C := by dsimp [C]; linarith
  refine ⟨C, hC, ?_⟩
  have hlog : Tendsto (fun n : ℕ ↦ Real.log (n : ℝ)) atTop atTop :=
    Real.tendsto_log_atTop.comp tendsto_natCast_atTop_atTop
  filter_upwards [eventually_gaussianNetHellingerSqError_256_le_inv_pow6 d hS,
    eventually_gaussianNetLogError_256_le_inv_pow3 d hS hβ,
    eventually_gaussianMomentRelativeError_256_le_half d hS hβ,
    eventually_gaussianPaper_weightSmall d (C := (256 : ℝ)) hS hβ,
    eventually_log_gaussianNetCardBound_paper_le d (show (0 : ℝ) < 256 by norm_num) hS,
    eventually_gaussianPaperSampleRadius_le_sqrt_log d hS hβ,
    eventually_gaussianPaperLogScale_nonneg_le_log,
    hlog.eventually_ge_atTop 1,
    tendsto_natCast_atTop_atTop.eventually_ge_atTop (2 * (d : ℝ) + 1),
    Filter.eventually_ge_atTop (1 : ℕ)]
      with n hSq hδ hhalf hsmall hent hRadius hscale hlogn hdn hn
  have hnpos : 0 < n := by omega
  have hnreal : (0 : ℝ) < n := by exact_mod_cast hnpos
  let L := gaussianPaperMomentOrder 256 n
  let M := gaussianPaperWeightDenominator d 256 n
  let ε := gaussianPaperEpsilon n
  let T := gaussianPaperSampleRadius d S β n
  have hT : 0 ≤ T := by dsimp [T, gaussianPaperSampleRadius]; positivity
  have hε : 0 < ε := gaussianPaperEpsilon_pos hnpos
  let Q := boundedLocationNet K hKnonempty S ε hε hKbound
  let N := finiteGaussianMixtureGrid d (gaussianMomentDimension d L) M Q
  have happrox : ∀ G : ProbabilityMeasure K, ∃ p ∈ N,
      Real.sqrt (hellingerSq volume p (compactGaussianMixtureDensity G)) ≤ 1 / (n : ℝ) ^ 3 ∧
      ∀ y : Point d, ‖y‖ ≤ T →
        |Real.log (p y) - Real.log (compactGaussianMixtureDensity G y)| ≤ 1 / (n : ℝ) ^ 3 := by
    intro G
    obtain ⟨p, hp, hpSq, hpδ⟩ := exists_mem_boundedGaussianMixtureGrid_simultaneous_approximation
      (G : Measure K) (fun a : K ↦ (a : Point d)) measurable_subtype_coe K
      {y | ‖y‖ ≤ T} hKcompact hKnonempty (fun a ↦ a.property)
      hT hS hε hKbound (fun _ hy ↦ hy) (gaussianPaperWeightDenominator_pos d 256 hnpos)
      hhalf (by simpa only [gaussianPaperTaylorArgument] using hsmall)
    refine ⟨p, hp, ?_, fun y hy ↦ (hpδ y hy).trans hδ⟩
    have hpSq' : hellingerSq volume p (compactGaussianMixtureDensity G) ≤ 1 / (n : ℝ) ^ 6 := by
      have hsymm : hellingerSq volume p (compactGaussianMixtureDensity G) =
          hellingerSq volume (compactGaussianMixtureDensity G) p := by
        unfold hellingerSq
        congr 1
        funext y
        ring
      rw [hsymm]
      exact hpSq.trans hSq
    have hsqrt := Real.sqrt_le_sqrt hpSq'
    have hsquare : 1 / (n : ℝ) ^ 6 = (1 / (n : ℝ) ^ 3) ^ 2 := by field_simp
    simpa only [hsquare, Real.sqrt_sq (by positivity : 0 ≤ 1 / (n : ℝ) ^ 3)] using hsqrt
  have hKn := hKnonempty
  obtain ⟨θ₀, hθ₀⟩ := hKn
  let G₀ : ProbabilityMeasure K := ⟨Measure.dirac ⟨θ₀, hθ₀⟩, inferInstance⟩
  obtain ⟨p₀, hp₀, _⟩ := happrox G₀
  have hNnonempty : N.Nonempty := ⟨p₀, hp₀⟩
  have hcard : N.card ≤ gaussianNetCardBound d L M S ε :=
    card_finiteGaussianMixtureGrid_boundedLocationNet_le _ _ K hKnonempty hε hKbound
  have hent' : Real.log (N.card : ℝ) ≤ E * gaussianPaperLogScale n ^ d * Real.log n := by
    have hcardReal : (N.card : ℝ) ≤ (gaussianNetCardBound d L M S ε : ℝ) := by
      exact_mod_cast hcard
    apply (Real.log_le_log (by exact_mod_cast Finset.card_pos.mpr hNnonempty) hcardReal).trans
    simpa only [E, gaussianPaperEntropyConstant, show (4 * (256 : ℝ) + 1) = 1025 by norm_num]
      using hent
  have hEC : E ≤ C := by dsimp [C]; linarith
  have hRC : R ≤ C := by dsimp [C]; linarith
  refine ⟨N, T, hNnonempty, hT, ?_, ?_, ?_, ?_, happrox⟩
  · exact hRadius.trans (mul_le_mul_of_nonneg_right hRC (Real.sqrt_nonneg _))
  · have hbound : Real.log (N.card : ℝ) ≤ C * gaussianPaperLogScale n ^ d * Real.log n := by
      apply hent'.trans
      exact mul_le_mul_of_nonneg_right
        (mul_le_mul_of_nonneg_right hEC (pow_nonneg hscale.1 _)) (by linarith)
    convert hbound using 1 <;> simp only [gaussianPaperLogScale, div_pow] <;> ring
  · intro p hp
    exact mem_gaussianGrid_is_compactGaussianMixtureDensity hKcompact Q
      (boundedLocationNet_subset K hKnonempty hε hKbound) hp
  · intro Gstar
    exact compactGaussianSampleMeasure_strengthened_paper_radius_tail Gstar hS hb.le hKbound
      (by linarith) hn hdn

end ReweightedNPMLE
