import Mathlib.MeasureTheory.Measure.ProbabilityMeasure
import ReweightedNPMLE.GaussianFiniteNet
import ReweightedNPMLE.FiniteNet
import ReweightedNPMLE.GaussianRadius

/-!
# Uniform near-MLE control for compact Gaussian mixtures

This module closes the main interface between the analytic Gaussian-mixture
net and the finite likelihood-ratio test.  Candidates are genuine bundled
probability measures on a compact location set, rather than a finite-mixture
surrogate parameterization.
-/

open scoped BigOperators ENNReal
open MeasureTheory Set

namespace ReweightedNPMLE

/-- The density of the Gaussian location mixture generated by a probability
measure on the subtype `K`. -/
noncomputable def compactGaussianMixtureDensity {d : ℕ}
    {K : Set (Point d)} (G : ProbabilityMeasure K) : Point d → ℝ :=
  gaussianMixture (G : Measure K) (fun θ : K ↦ (θ : Point d))

theorem compactGaussianMixtureDensity_measurable {d : ℕ}
    {K : Set (Point d)} (G : ProbabilityMeasure K) :
    Measurable (compactGaussianMixtureDensity G) := by
  exact measurable_gaussianMixture (G : Measure K)
    (fun θ : K ↦ (θ : Point d)) measurable_subtype_coe

theorem compactGaussianMixtureDensity_pos {d : ℕ}
    {K : Set (Point d)} (G : ProbabilityMeasure K) (x : Point d) :
    0 < compactGaussianMixtureDensity G x := by
  exact gaussianMixture_pos (G : Measure K)
    (fun θ : K ↦ (θ : Point d)) measurable_subtype_coe x

theorem compactGaussianMixtureDensity_integrable {d : ℕ}
    {K : Set (Point d)} (G : ProbabilityMeasure K) :
    Integrable (compactGaussianMixtureDensity G) := by
  exact gaussianMixture_integrable (G : Measure K)
    (fun θ : K ↦ (θ : Point d)) measurable_subtype_coe

theorem integral_compactGaussianMixtureDensity {d : ℕ}
    {K : Set (Point d)} (G : ProbabilityMeasure K) :
    ∫ x, compactGaussianMixtureDensity G x = 1 := by
  exact integral_gaussianMixture (G : Measure K)
    (fun θ : K ↦ (θ : Point d)) measurable_subtype_coe

/-- The direct squared-Hellinger error delivered by moment matching, location
rounding, and simplex rounding. -/
noncomputable def gaussianNetHellingerSqError
    (d L M : ℕ) (S ε : ℝ) : ℝ :=
  2 * gaussianMomentHellingerError S L + ε ^ 2 +
    4 * (2 * gaussianMomentDimension d L / M)

/-- The uniform log-density error on the sample-radius set. -/
noncomputable def gaussianNetLogError
    (d L M : ℕ) (T S ε : ℝ) : ℝ :=
  (T + S) * ε +
    2 * Real.exp (2 * (T * S + S ^ 2 / 2)) *
      (2 * gaussianMomentDimension d L / M) +
    2 * gaussianMomentRelativeError T S L

/-- Explicit upper bound on the number of densities in the rounded Gaussian
mixture grid. -/
noncomputable def gaussianNetCardBound
    (d L M : ℕ) (S ε : ℝ) : ℕ :=
  ((boundedLocationCellCount d S ε) ^ d) ^
      (gaussianMomentDimension d L + 1) *
    (M + 1) ^ gaussianMomentDimension d L

theorem gaussianNetCardBound_pos (d L M : ℕ) (S ε : ℝ) :
    0 < gaussianNetCardBound d L M S ε := by
  unfold gaussianNetCardBound boundedLocationCellCount
  positivity

/-- Uniform likelihood/Hellinger control for every near-MLE over all mixing
laws supported on a compact location set, using any supplied finite internal
location cover. -/
theorem compactGaussianMixture_uniform_nearMLE_bad_event_bound_of_cover
    {d L M n : ℕ}
    (K X : Set (Point d)) (Q : Finset (Point d))
    (hKcompact : IsCompact K) (hKnonempty : K.Nonempty)
    {T S ε : ℝ} (hT : 0 ≤ T) (hS : 0 ≤ S) (hε : 0 < ε)
    (hKbound : ∀ u ∈ K, ‖u‖ ≤ S) (hXbound : ∀ x ∈ X, ‖x‖ ≤ T)
    (hQK : ↑Q ⊆ K)
    (hQcover : ∀ u ∈ K, ∃ v ∈ Q, ‖u - v‖ ≤ ε)
    (hM : 0 < M)
    (hrelativeHalf : gaussianMomentRelativeError T S L ≤ 1 / 2)
    (hweightSmall : Real.exp (2 * (T * S + S ^ 2 / 2)) *
      (2 * gaussianMomentDimension d L / M) ≤ 1 / 2)
    (Gstar : ProbabilityMeasure K) (t radiusBound : ℝ)
    (hnδ : (n : ℝ) * gaussianNetLogError d L M T S ε ≤ 1)
    (hradius :
      (Measure.pi (fun _ : Fin n ↦ volume.withDensity (fun y ↦
        ENNReal.ofReal (compactGaussianMixtureDensity Gstar y)))).real
          ({x : Fin n → Point d | ∀ i, x i ∈ X}ᶜ) ≤ radiusBound) :
    (Measure.pi (fun _ : Fin n ↦ volume.withDensity (fun y ↦
      ENNReal.ofReal (compactGaussianMixtureDensity Gstar y)))).real
        {x | ∃ G : ProbabilityMeasure K,
          (∑ i, Real.log (compactGaussianMixtureDensity Gstar (x i))) - 1 ≤
              ∑ i, Real.log (compactGaussianMixtureDensity G (x i)) ∧
          2 * gaussianNetHellingerSqError d L M S ε + 2 * t ^ 2 <
            hellingerSq volume (compactGaussianMixtureDensity G)
              (compactGaussianMixtureDensity Gstar)} ≤
      radiusBound +
        (Q.card ^ (gaussianMomentDimension d L + 1) * (M + 1) ^
              gaussianMomentDimension d L) *
          Real.exp (1 - (n : ℝ) * t ^ 2 / 2) := by
  classical
  let k := gaussianMomentDimension d L
  let N := finiteGaussianMixtureGrid d k M Q
  let f : ProbabilityMeasure K → Point d → ℝ :=
    fun G ↦ compactGaussianMixtureDensity G
  let q : Point d → ℝ := compactGaussianMixtureDensity Gstar
  let δ := gaussianNetLogError d L M T S ε
  let globalSq := gaussianNetHellingerSqError d L M S ε
  have happ : ∀ G : ProbabilityMeasure K, ∃ p ∈ N,
      hellingerSq volume (f G) p ≤ globalSq ∧
      ∀ x ∈ X, |Real.log (p x) - Real.log (f G x)| ≤ δ := by
    intro G
    simpa only [N, k, f, δ, globalSq,
      compactGaussianMixtureDensity, gaussianNetHellingerSqError,
      gaussianNetLogError] using
      (exists_mem_finiteGaussianMixtureGrid_simultaneous_approximation_of_cover
        (G : Measure K) (fun θ : K ↦ (θ : Point d))
        measurable_subtype_coe K X Q hKcompact hKnonempty
        (fun θ : K ↦ θ.property) hT hS hε hKbound hXbound hQK hQcover hM
        hrelativeHalf hweightSmall)
  let select : ProbabilityMeasure K → (Point d → ℝ) :=
    fun G ↦ (happ G).choose
  have hselect : ∀ G, select G ∈ N := fun G ↦ (happ G).choose_spec.1
  have hglobal : ∀ G,
      hellingerSq volume (f G) (select G) ≤ globalSq :=
    fun G ↦ (happ G).choose_spec.2.1
  have hlocal : ∀ G x, x ∈ X →
      |Real.log (select G x) - Real.log (f G x)| ≤ δ :=
    fun G ↦ (happ G).choose_spec.2.2
  have hqmeas : Measurable q := compactGaussianMixtureDensity_measurable Gstar
  have hq : ∀ x, 0 < q x := compactGaussianMixtureDensity_pos Gstar
  have hqint : Integrable q := compactGaussianMixtureDensity_integrable Gstar
  have hqone : ∫ x, q x = 1 := integral_compactGaussianMixtureDensity Gstar
  have hmain := uniform_nearMLE_hellinger_bad_event_bound
    volume N (fun p : Point d → ℝ ↦ p) q f select
    {x : Fin n → Point d | ∀ i, x i ∈ X} δ globalSq t radiusBound
    hqmeas hq hqint hqone
    (fun p hp ↦ finiteGaussianMixtureGrid_pos Q hp)
    (fun p hp ↦ finiteGaussianMixtureGrid_integrable Q hp)
    (fun p hp ↦ sqrt_mul_integrable_of_integrable volume p q
      (finiteGaussianMixtureGrid_integrable Q hp).aestronglyMeasurable
      hqint.aestronglyMeasurable
      (Filter.Eventually.of_forall fun x ↦
        (finiteGaussianMixtureGrid_pos Q hp x).le)
      (Filter.Eventually.of_forall fun x ↦ (hq x).le)
      (finiteGaussianMixtureGrid_integrable Q hp) hqint)
    (fun p hp ↦ integral_finiteGaussianMixtureGrid Q hp)
    (fun G ↦ compactGaussianMixtureDensity_pos G)
    (fun G ↦ compactGaussianMixtureDensity_integrable G)
    hselect hglobal
    (fun x hx G i ↦ hlocal G (x i) (hx i)) hnδ hradius
  have hcardNat : N.card ≤ Q.card ^ (k + 1) * (M + 1) ^ k := by
    exact card_finiteGaussianMixtureGrid_le d k M Q
  have hcard : (N.card : ℝ) ≤
      (Q.card : ℝ) ^ (k + 1) * ((M : ℝ) + 1) ^ k := by
    exact_mod_cast hcardNat
  have hmul : (N.card : ℝ) * Real.exp (1 - (n : ℝ) * t ^ 2 / 2) ≤
      (Q.card : ℝ) ^ (k + 1) * ((M : ℝ) + 1) ^ k *
        Real.exp (1 - (n : ℝ) * t ^ 2 / 2) :=
    mul_le_mul_of_nonneg_right hcard (Real.exp_pos _).le
  exact hmain.trans (by
    simpa only [N, k, f, q, δ, globalSq] using
      add_le_add (le_refl radiusBound) hmul)

/-- Uniform near-MLE control using the compactness-generated internal cover. -/
theorem compactGaussianMixture_uniform_nearMLE_bad_event_bound
    {d L M n : ℕ}
    (K X : Set (Point d))
    (hKcompact : IsCompact K) (hKnonempty : K.Nonempty)
    {T S ε : ℝ} (hT : 0 ≤ T) (hS : 0 ≤ S) (hε : 0 < ε)
    (hKbound : ∀ u ∈ K, ‖u‖ ≤ S) (hXbound : ∀ x ∈ X, ‖x‖ ≤ T)
    (hM : 0 < M)
    (hrelativeHalf : gaussianMomentRelativeError T S L ≤ 1 / 2)
    (hweightSmall : Real.exp (2 * (T * S + S ^ 2 / 2)) *
      (2 * gaussianMomentDimension d L / M) ≤ 1 / 2)
    (Gstar : ProbabilityMeasure K) (t radiusBound : ℝ)
    (hnδ : (n : ℝ) * gaussianNetLogError d L M T S ε ≤ 1)
    (hradius :
      (Measure.pi (fun _ : Fin n ↦ volume.withDensity (fun y ↦
        ENNReal.ofReal (compactGaussianMixtureDensity Gstar y)))).real
          ({x : Fin n → Point d | ∀ i, x i ∈ X}ᶜ) ≤ radiusBound) :
    (Measure.pi (fun _ : Fin n ↦ volume.withDensity (fun y ↦
      ENNReal.ofReal (compactGaussianMixtureDensity Gstar y)))).real
        {x | ∃ G : ProbabilityMeasure K,
          (∑ i, Real.log (compactGaussianMixtureDensity Gstar (x i))) - 1 ≤
              ∑ i, Real.log (compactGaussianMixtureDensity G (x i)) ∧
          2 * gaussianNetHellingerSqError d L M S ε + 2 * t ^ 2 <
            hellingerSq volume (compactGaussianMixtureDensity G)
              (compactGaussianMixtureDensity Gstar)} ≤
      radiusBound +
        ((compactLocationNet K hKcompact ε hε).card ^
            (gaussianMomentDimension d L + 1) * (M + 1) ^
              gaussianMomentDimension d L) *
          Real.exp (1 - (n : ℝ) * t ^ 2 / 2) := by
  apply compactGaussianMixture_uniform_nearMLE_bad_event_bound_of_cover
    K X (compactLocationNet K hKcompact ε hε) hKcompact hKnonempty
    hT hS hε hKbound hXbound
    (compactLocationNet_subset K hKcompact ε hε) _ hM
    hrelativeHalf hweightSmall Gstar t radiusBound hnδ hradius
  intro u hu
  obtain ⟨v, hv, huv⟩ :=
    exists_mem_compactLocationNet_dist_lt K hKcompact hε hu
  exact ⟨v, hv, by simpa only [dist_eq_norm] using huv.le⟩

/-- Uniform near-MLE control with the coordinate-cell location entropy made
fully explicit. -/
theorem compactGaussianMixture_uniform_nearMLE_bad_event_bound_bounded
    {d L M n : ℕ}
    (K X : Set (Point d))
    (hKcompact : IsCompact K) (hKnonempty : K.Nonempty)
    {T S ε : ℝ} (hT : 0 ≤ T) (hS : 0 ≤ S) (hε : 0 < ε)
    (hKbound : ∀ u ∈ K, ‖u‖ ≤ S) (hXbound : ∀ x ∈ X, ‖x‖ ≤ T)
    (hM : 0 < M)
    (hrelativeHalf : gaussianMomentRelativeError T S L ≤ 1 / 2)
    (hweightSmall : Real.exp (2 * (T * S + S ^ 2 / 2)) *
      (2 * gaussianMomentDimension d L / M) ≤ 1 / 2)
    (Gstar : ProbabilityMeasure K) (t radiusBound : ℝ)
    (hnδ : (n : ℝ) * gaussianNetLogError d L M T S ε ≤ 1)
    (hradius :
      (Measure.pi (fun _ : Fin n ↦ volume.withDensity (fun y ↦
        ENNReal.ofReal (compactGaussianMixtureDensity Gstar y)))).real
          ({x : Fin n → Point d | ∀ i, x i ∈ X}ᶜ) ≤ radiusBound) :
    (Measure.pi (fun _ : Fin n ↦ volume.withDensity (fun y ↦
      ENNReal.ofReal (compactGaussianMixtureDensity Gstar y)))).real
        {x | ∃ G : ProbabilityMeasure K,
          (∑ i, Real.log (compactGaussianMixtureDensity Gstar (x i))) - 1 ≤
              ∑ i, Real.log (compactGaussianMixtureDensity G (x i)) ∧
          2 * gaussianNetHellingerSqError d L M S ε + 2 * t ^ 2 <
            hellingerSq volume (compactGaussianMixtureDensity G)
              (compactGaussianMixtureDensity Gstar)} ≤
      radiusBound +
        (((boundedLocationCellCount d S ε) ^ d) ^
            (gaussianMomentDimension d L + 1) * (M + 1) ^
              gaussianMomentDimension d L) *
          Real.exp (1 - (n : ℝ) * t ^ 2 / 2) := by
  let Q := boundedLocationNet K hKnonempty S ε hε hKbound
  have hmain := compactGaussianMixture_uniform_nearMLE_bad_event_bound_of_cover
    K X Q hKcompact hKnonempty hT hS hε hKbound hXbound
    (boundedLocationNet_subset K hKnonempty hε hKbound)
    (exists_mem_boundedLocationNet_norm_sub_le K hKnonempty hε hKbound)
    hM hrelativeHalf hweightSmall Gstar t radiusBound hnδ hradius
  refine hmain.trans (add_le_add_right ?_ radiusBound)
  have hcard : Q.card ≤ (boundedLocationCellCount d S ε) ^ d := by
    exact card_boundedLocationNet_le K hKnonempty hε hKbound
  have hcardReal : (Q.card : ℝ) ≤
      ((boundedLocationCellCount d S ε) ^ d : ℕ) := by
    exact_mod_cast hcard
  have hcardReal' : (Q.card : ℝ) ≤
      (boundedLocationCellCount d S ε : ℝ) ^ d := by
    simpa only [Nat.cast_pow] using hcardReal
  gcongr

/-- Fully explicit radius specialization of
`compactGaussianMixture_uniform_nearMLE_bad_event_bound`.  The sample-radius
failure term is discharged under the true compact Gaussian mixture law and
is `2 n d exp (-r²/2)`. -/
theorem compactGaussianMixture_uniform_nearMLE_bad_event_bound_explicit
    {d L M n : ℕ}
    (K : Set (Point d))
    (hKcompact : IsCompact K) (hKnonempty : K.Nonempty)
    {S ε r : ℝ} (hS : 0 ≤ S) (hε : 0 < ε) (hr : 0 < r)
    (hKbound : ∀ u ∈ K, ‖u‖ ≤ S)
    (hM : 0 < M)
    (hrelativeHalf : gaussianMomentRelativeError
      (S + Real.sqrt d * r) S L ≤ 1 / 2)
    (hweightSmall : Real.exp
      (2 * ((S + Real.sqrt d * r) * S + S ^ 2 / 2)) *
        (2 * gaussianMomentDimension d L / M) ≤ 1 / 2)
    (Gstar : ProbabilityMeasure K) (t : ℝ)
    (hnδ : (n : ℝ) * gaussianNetLogError d L M
      (S + Real.sqrt d * r) S ε ≤ 1) :
    (Measure.pi (fun _ : Fin n ↦ volume.withDensity (fun y ↦
      ENNReal.ofReal (compactGaussianMixtureDensity Gstar y)))).real
        {x | ∃ G : ProbabilityMeasure K,
          (∑ i, Real.log (compactGaussianMixtureDensity Gstar (x i))) - 1 ≤
              ∑ i, Real.log (compactGaussianMixtureDensity G (x i)) ∧
          2 * gaussianNetHellingerSqError d L M S ε + 2 * t ^ 2 <
            hellingerSq volume (compactGaussianMixtureDensity G)
              (compactGaussianMixtureDensity Gstar)} ≤
      2 * n * d * Real.exp (-r ^ 2 / 2) +
        (((boundedLocationCellCount d S ε) ^ d) ^
            (gaussianMomentDimension d L + 1) * (M + 1) ^
              gaussianMomentDimension d L) *
          Real.exp (1 - (n : ℝ) * t ^ 2 / 2) := by
  let R : ℝ := S + Real.sqrt d * r
  have hR : 0 ≤ R := by
    dsimp [R]
    positivity
  have htail := gaussianLocationMixtureSample_max_radius_tail
    (n := n) (Gstar : Measure K) (fun θ : K ↦ (θ : Point d))
    measurable_subtype_coe (S := S) (t := r)
    (fun θ ↦ hKbound θ θ.property) hr
  rw [gaussianLocationMixtureLaw_eq_withDensity_gaussianMixture
    (Gstar : Measure K) (fun θ : K ↦ (θ : Point d))
      measurable_subtype_coe] at htail
  have hbad : ({x : Fin n → Point d | ∀ i, x i ∈
      {y : Point d | ‖y‖ ≤ R}}ᶜ) =
      {x : Fin n → Point d | ∃ i, ‖x i‖ > R} := by
    ext x
    simp only [Set.mem_compl_iff, Set.mem_setOf_eq]
    push Not
    rfl
  have hradius :
      (Measure.pi (fun _ : Fin n ↦ volume.withDensity (fun y ↦
        ENNReal.ofReal (compactGaussianMixtureDensity Gstar y)))).real
          ({x : Fin n → Point d | ∀ i, x i ∈
            {y : Point d | ‖y‖ ≤ R}}ᶜ) ≤
        2 * n * d * Real.exp (-r ^ 2 / 2) := by
    rw [hbad]
    simpa only [compactGaussianMixtureDensity, R] using htail
  simpa only [R] using
    (compactGaussianMixture_uniform_nearMLE_bad_event_bound_bounded
      K {x : Point d | ‖x‖ ≤ R} hKcompact hKnonempty
      hR hS hε hKbound (fun x hx ↦ hx) hM hrelativeHalf hweightSmall
      Gstar t (2 * n * d * Real.exp (-r ^ 2 / 2)) hnδ hradius)

/-- The fully explicit radius theorem with the likelihood-test threshold
chosen as `t = sqrt (2A/n)`.  The squared-Hellinger cutoff becomes
`2·globalSq + 4A/n`, and the finite-net failure factor becomes
`cardBound · exp (1-A)`. -/
theorem compactGaussianMixture_uniform_nearMLE_bad_event_bound_explicit_tuned
    {d L M n : ℕ} (hn : 0 < n)
    (K : Set (Point d))
    (hKcompact : IsCompact K) (hKnonempty : K.Nonempty)
    {S ε r A : ℝ} (hS : 0 ≤ S) (hε : 0 < ε) (hr : 0 < r)
    (hA : 0 ≤ A)
    (hKbound : ∀ u ∈ K, ‖u‖ ≤ S)
    (hM : 0 < M)
    (hrelativeHalf : gaussianMomentRelativeError
      (S + Real.sqrt d * r) S L ≤ 1 / 2)
    (hweightSmall : Real.exp
      (2 * ((S + Real.sqrt d * r) * S + S ^ 2 / 2)) *
        (2 * gaussianMomentDimension d L / M) ≤ 1 / 2)
    (Gstar : ProbabilityMeasure K)
    (hnδ : (n : ℝ) * gaussianNetLogError d L M
      (S + Real.sqrt d * r) S ε ≤ 1) :
    (Measure.pi (fun _ : Fin n ↦ volume.withDensity (fun y ↦
      ENNReal.ofReal (compactGaussianMixtureDensity Gstar y)))).real
        {x | ∃ G : ProbabilityMeasure K,
          (∑ i, Real.log (compactGaussianMixtureDensity Gstar (x i))) - 1 ≤
              ∑ i, Real.log (compactGaussianMixtureDensity G (x i)) ∧
          2 * gaussianNetHellingerSqError d L M S ε +
              4 * A / n <
            hellingerSq volume (compactGaussianMixtureDensity G)
              (compactGaussianMixtureDensity Gstar)} ≤
      2 * n * d * Real.exp (-r ^ 2 / 2) +
        (((boundedLocationCellCount d S ε) ^ d) ^
            (gaussianMomentDimension d L + 1) * (M + 1) ^
              gaussianMomentDimension d L) * Real.exp (1 - A) := by
  let t : ℝ := Real.sqrt (2 * A / n)
  have hnreal : (0 : ℝ) < n := by exact_mod_cast hn
  have harg : 0 ≤ 2 * A / (n : ℝ) := by positivity
  have htSq : t ^ 2 = 2 * A / n := by
    exact Real.sq_sqrt harg
  have hmain :=
    compactGaussianMixture_uniform_nearMLE_bad_event_bound_explicit
      K hKcompact hKnonempty hS hε hr hKbound hM
      hrelativeHalf hweightSmall Gstar t hnδ
  simpa only [htSq, show 2 * (2 * A / (n : ℝ)) = 4 * A / n by ring,
    show 1 - (n : ℝ) * (2 * A / n) / 2 = 1 - A by
      field_simp] using hmain

/-- Entropy-calibrated form of the near-MLE theorem.  Taking
`A = log(cardBound) + B + 2` reduces the entire likelihood-test failure term
to `exp(-B-1)`. -/
theorem compactGaussianMixture_uniform_nearMLE_bad_event_bound_entropy_tuned
    {d L M n : ℕ} (hn : 0 < n)
    (K : Set (Point d))
    (hKcompact : IsCompact K) (hKnonempty : K.Nonempty)
    {S ε r B : ℝ} (hS : 0 ≤ S) (hε : 0 < ε) (hr : 0 < r)
    (hB : 0 ≤ B)
    (hKbound : ∀ u ∈ K, ‖u‖ ≤ S)
    (hM : 0 < M)
    (hrelativeHalf : gaussianMomentRelativeError
      (S + Real.sqrt d * r) S L ≤ 1 / 2)
    (hweightSmall : Real.exp
      (2 * ((S + Real.sqrt d * r) * S + S ^ 2 / 2)) *
        (2 * gaussianMomentDimension d L / M) ≤ 1 / 2)
    (Gstar : ProbabilityMeasure K)
    (hnδ : (n : ℝ) * gaussianNetLogError d L M
      (S + Real.sqrt d * r) S ε ≤ 1) :
    (Measure.pi (fun _ : Fin n ↦ volume.withDensity (fun y ↦
      ENNReal.ofReal (compactGaussianMixtureDensity Gstar y)))).real
        {x | ∃ G : ProbabilityMeasure K,
          (∑ i, Real.log (compactGaussianMixtureDensity Gstar (x i))) - 1 ≤
              ∑ i, Real.log (compactGaussianMixtureDensity G (x i)) ∧
          2 * gaussianNetHellingerSqError d L M S ε +
              4 * (Real.log (gaussianNetCardBound d L M S ε) + B + 2) / n <
            hellingerSq volume (compactGaussianMixtureDensity G)
              (compactGaussianMixtureDensity Gstar)} ≤
      2 * n * d * Real.exp (-r ^ 2 / 2) + Real.exp (-B - 1) := by
  let C : ℝ := gaussianNetCardBound d L M S ε
  let A : ℝ := Real.log C + B + 2
  have hC : 0 < C := by
    dsimp [C]
    exact_mod_cast gaussianNetCardBound_pos d L M S ε
  have hlogC : 0 ≤ Real.log C :=
    Real.log_nonneg (by
      dsimp [C]
      exact_mod_cast (Nat.one_le_iff_ne_zero.mpr
        (gaussianNetCardBound_pos d L M S ε).ne'))
  have hA : 0 ≤ A := by
    dsimp [A]
    positivity
  have hmain :=
    compactGaussianMixture_uniform_nearMLE_bad_event_bound_explicit_tuned
      hn K hKcompact hKnonempty hS hε hr hA hKbound hM
      hrelativeHalf hweightSmall Gstar hnδ
  have hfactor : C * Real.exp (1 - A) = Real.exp (-B - 1) := by
    rw [show C = Real.exp (Real.log C) by rw [Real.exp_log hC]]
    rw [← Real.exp_add]
    congr 1
    dsimp [A]
    ring
  have hCeq : C =
      ((boundedLocationCellCount d S ε : ℝ) ^ d) ^
          (gaussianMomentDimension d L + 1) *
        ((M : ℝ) + 1) ^ gaussianMomentDimension d L := by
    dsimp [C, gaussianNetCardBound]
    push_cast
    rfl
  have hfactor' :
      ((boundedLocationCellCount d S ε : ℝ) ^ d) ^
          (gaussianMomentDimension d L + 1) *
          ((M : ℝ) + 1) ^ gaussianMomentDimension d L *
            Real.exp (1 - A) = Real.exp (-B - 1) := by
    rw [← hCeq]
    exact hfactor
  rw [hfactor'] at hmain
  simpa only [C, A, gaussianNetCardBound] using hmain

/-- Both probabilistic tuning parameters are now expressed as exponents.
Taking `r = sqrt (2R)` gives the radius failure term
`2 n d exp(-R)`, while the entropy-calibrated likelihood-test term remains
`exp(-B-1)`. -/
theorem compactGaussianMixture_uniform_nearMLE_bad_event_bound_fully_tuned
    {d L M n : ℕ} (hn : 0 < n)
    (K : Set (Point d))
    (hKcompact : IsCompact K) (hKnonempty : K.Nonempty)
    {S ε R B : ℝ} (hS : 0 ≤ S) (hε : 0 < ε) (hR : 0 < R)
    (hB : 0 ≤ B)
    (hKbound : ∀ u ∈ K, ‖u‖ ≤ S)
    (hM : 0 < M)
    (hrelativeHalf : gaussianMomentRelativeError
      (S + Real.sqrt d * Real.sqrt (2 * R)) S L ≤ 1 / 2)
    (hweightSmall : Real.exp
      (2 * ((S + Real.sqrt d * Real.sqrt (2 * R)) * S + S ^ 2 / 2)) *
        (2 * gaussianMomentDimension d L / M) ≤ 1 / 2)
    (Gstar : ProbabilityMeasure K)
    (hnδ : (n : ℝ) * gaussianNetLogError d L M
      (S + Real.sqrt d * Real.sqrt (2 * R)) S ε ≤ 1) :
    (Measure.pi (fun _ : Fin n ↦ volume.withDensity (fun y ↦
      ENNReal.ofReal (compactGaussianMixtureDensity Gstar y)))).real
        {x | ∃ G : ProbabilityMeasure K,
          (∑ i, Real.log (compactGaussianMixtureDensity Gstar (x i))) - 1 ≤
              ∑ i, Real.log (compactGaussianMixtureDensity G (x i)) ∧
          2 * gaussianNetHellingerSqError d L M S ε +
              4 * (Real.log (gaussianNetCardBound d L M S ε) + B + 2) / n <
            hellingerSq volume (compactGaussianMixtureDensity G)
              (compactGaussianMixtureDensity Gstar)} ≤
      2 * n * d * Real.exp (-R) + Real.exp (-B - 1) := by
  let r : ℝ := Real.sqrt (2 * R)
  have h2R : 0 ≤ 2 * R := by positivity
  have hr : 0 < r := by
    exact Real.sqrt_pos.2 (by positivity)
  have hrSq : r ^ 2 = 2 * R := Real.sq_sqrt h2R
  have hmain :=
    compactGaussianMixture_uniform_nearMLE_bad_event_bound_entropy_tuned
      hn K hKcompact hKnonempty hS hε hr hB hKbound hM
      hrelativeHalf hweightSmall Gstar hnδ
  simpa only [r, hrSq, show -(2 * R) / 2 = -R by ring] using hmain

/-- Polynomial-tail calibration used in the paper.  With
`B = (b+2) log n` and `R = log(2nd)+B`, the radius and likelihood-test
failure terms are respectively `exp(-B)` and `exp(-B-1)`. -/
theorem compactGaussianMixture_uniform_nearMLE_bad_event_bound_polynomial_tuned
    {d L M n : ℕ} (hn : 2 ≤ n) (hd : 0 < d)
    (K : Set (Point d))
    (hKcompact : IsCompact K) (hKnonempty : K.Nonempty)
    {S ε b : ℝ} (hS : 0 ≤ S) (hε : 0 < ε) (hb : 0 ≤ b)
    (hKbound : ∀ u ∈ K, ‖u‖ ≤ S)
    (hM : 0 < M)
    (hrelativeHalf : gaussianMomentRelativeError
      (S + Real.sqrt d * Real.sqrt
        (2 * (Real.log ((2 : ℝ) * n * d) + (b + 2) * Real.log n))) S L ≤
          1 / 2)
    (hweightSmall : Real.exp
      (2 * ((S + Real.sqrt d * Real.sqrt
        (2 * (Real.log ((2 : ℝ) * n * d) + (b + 2) * Real.log n))) * S +
          S ^ 2 / 2)) *
        (2 * gaussianMomentDimension d L / M) ≤ 1 / 2)
    (Gstar : ProbabilityMeasure K)
    (hnδ : (n : ℝ) * gaussianNetLogError d L M
      (S + Real.sqrt d * Real.sqrt
        (2 * (Real.log ((2 : ℝ) * n * d) + (b + 2) * Real.log n))) S ε ≤ 1) :
    (Measure.pi (fun _ : Fin n ↦ volume.withDensity (fun y ↦
      ENNReal.ofReal (compactGaussianMixtureDensity Gstar y)))).real
        {x | ∃ G : ProbabilityMeasure K,
          (∑ i, Real.log (compactGaussianMixtureDensity Gstar (x i))) - 1 ≤
              ∑ i, Real.log (compactGaussianMixtureDensity G (x i)) ∧
          2 * gaussianNetHellingerSqError d L M S ε +
              4 * (Real.log (gaussianNetCardBound d L M S ε) +
                (b + 2) * Real.log n + 2) / n <
            hellingerSq volume (compactGaussianMixtureDensity G)
              (compactGaussianMixtureDensity Gstar)} ≤
      Real.exp (-(b + 2) * Real.log n) +
        Real.exp (-(b + 2) * Real.log n - 1) := by
  let B : ℝ := (b + 2) * Real.log n
  let C : ℝ := (2 : ℝ) * n * d
  let R : ℝ := Real.log C + B
  have hnpos : 0 < n := lt_of_lt_of_le (by omega) hn
  have hnreal : (0 : ℝ) < n := by exact_mod_cast hnpos
  have hnrealTwo : (2 : ℝ) ≤ n := by exact_mod_cast hn
  have hdreal : (0 : ℝ) < d := by exact_mod_cast hd
  have hdone : (1 : ℝ) ≤ d := by exact_mod_cast hd
  have hCfour : (4 : ℝ) ≤ C := by
    dsimp [C]
    calc
      (4 : ℝ) = 2 * 2 * 1 := by ring
      _ ≤ 2 * (n : ℝ) * d := by gcongr
  have hC : 0 < C := lt_of_lt_of_le (by norm_num) hCfour
  have hCgt : 1 < C := lt_of_lt_of_le (by norm_num) hCfour
  have hB : 0 ≤ B := by
    dsimp [B]
    have hlogn : 0 ≤ Real.log (n : ℝ) :=
      Real.log_nonneg (by linarith)
    positivity
  have hR : 0 < R := by
    dsimp [R]
    exact add_pos_of_pos_of_nonneg (Real.log_pos hCgt) hB
  have hmain :=
    compactGaussianMixture_uniform_nearMLE_bad_event_bound_fully_tuned
      hnpos K hKcompact hKnonempty hS hε hR hB hKbound hM
      hrelativeHalf hweightSmall Gstar hnδ
  have hfactor : C * Real.exp (-R) = Real.exp (-B) := by
    rw [show C = Real.exp (Real.log C) by rw [Real.exp_log hC]]
    rw [← Real.exp_add]
    congr 1
    dsimp [R]
    ring
  rw [show (2 : ℝ) * n * d * Real.exp (-R) = Real.exp (-B) by
    simpa only [C] using hfactor] at hmain
  simpa only [C, R, B, neg_mul] using hmain

end ReweightedNPMLE
