import Mathlib.MeasureTheory.Integral.Prod
import Mathlib.MeasureTheory.Integral.IntegrableOn
import ReweightedNPMLE.Gaussian

/-!
# Gaussian mixtures indexed by probability measures

This module connects the finite-sum Gaussian algebra to the paper's original
parameter space of arbitrary compactly supported mixing laws.
-/

open scoped BigOperators RealInnerProductSpace
open MeasureTheory

namespace ReweightedNPMLE

/-- The Gaussian location-mixture density generated by a parameter map and a
mixing measure. -/
noncomputable def gaussianMixture {d : ℕ} {Θ : Type*} [MeasurableSpace Θ]
    (μ : Measure Θ) (θ : Θ → Point d) (x : Point d) : ℝ :=
  ∫ a, gaussianKernel d x (θ a) ∂μ

theorem gaussianKernel_le_constant {d : ℕ} (x θ : Point d) :
    gaussianKernel d x θ ≤ gaussianConstant d := by
  unfold gaussianKernel
  have he : Real.exp (-‖x - θ‖ ^ 2 / 2) ≤ Real.exp 0 := by
    exact Real.exp_le_exp.mpr (by nlinarith [sq_nonneg ‖x - θ‖])
  simpa using mul_le_mul_of_nonneg_left he (gaussianConstant_pos d).le

theorem gaussianKernel_comp_integrable
    {d : ℕ} {Θ : Type*} [MeasurableSpace Θ]
    (μ : Measure Θ) [IsFiniteMeasure μ]
    (θ : Θ → Point d) (hθ : Measurable θ) (x : Point d) :
    Integrable (fun a ↦ gaussianKernel d x (θ a)) μ := by
  exact Integrable.of_bound
    ((continuous_gaussianKernel d).measurable.comp
      (measurable_const.prodMk hθ)).aestronglyMeasurable
    (gaussianConstant d) (Filter.Eventually.of_forall fun a ↦ by
      rw [Real.norm_of_nonneg (gaussianKernel_pos d x (θ a)).le]
      exact gaussianKernel_le_constant x (θ a))

/-- Joint integrability of a probability mixture kernel over parameter and
observation space. -/
theorem gaussianKernel_comp_integrable_prod
    {d : ℕ} {Θ : Type*} [MeasurableSpace Θ]
    (μ : Measure Θ) [IsProbabilityMeasure μ]
    (θ : Θ → Point d) (hθ : Measurable θ) :
    Integrable (fun z : Θ × Point d ↦ gaussianKernel d z.2 (θ z.1))
      (μ.prod volume) := by
  have hmeas : AEStronglyMeasurable
      (fun z : Θ × Point d ↦ gaussianKernel d z.2 (θ z.1))
      (μ.prod volume) :=
    ((continuous_gaussianKernel d).measurable.comp
      (measurable_snd.prodMk (hθ.comp measurable_fst))).aestronglyMeasurable
  rw [integrable_prod_iff hmeas]
  constructor
  · exact Filter.Eventually.of_forall fun a ↦ gaussianKernel_integrable d (θ a)
  · have hfun : (fun a : Θ ↦
        ∫ x : Point d, ‖gaussianKernel d x (θ a)‖) = fun _ ↦ (1 : ℝ) := by
      funext a
      simp_rw [Real.norm_of_nonneg (gaussianKernel_pos d _ _).le]
      exact integral_gaussianKernel d (θ a)
    rw [hfun]
    exact integrable_const 1

theorem gaussianMixture_integrable
    {d : ℕ} {Θ : Type*} [MeasurableSpace Θ]
    (μ : Measure Θ) [IsProbabilityMeasure μ]
    (θ : Θ → Point d) (hθ : Measurable θ) :
    Integrable (gaussianMixture μ θ) := by
  exact (gaussianKernel_comp_integrable_prod μ θ hθ).integral_prod_right

/-- Every Gaussian location mixture is continuous in its observation
argument.  The Gaussian bound supplies an integrable dominator for an
arbitrary probability mixing law. -/
theorem continuous_gaussianMixture
    {d : ℕ} {Θ : Type*} [MeasurableSpace Θ]
    (μ : Measure Θ) [IsProbabilityMeasure μ]
    (θ : Θ → Point d) (hθ : Measurable θ) :
    Continuous (gaussianMixture μ θ) := by
  unfold gaussianMixture
  apply continuous_of_dominated (bound := fun _ ↦ gaussianConstant d)
  · intro x
    exact (gaussianKernel_comp_integrable μ θ hθ x).aestronglyMeasurable
  · intro x
    exact Filter.Eventually.of_forall fun a ↦ by
      rw [Real.norm_of_nonneg (gaussianKernel_pos d x (θ a)).le]
      exact gaussianKernel_le_constant x (θ a)
  · exact integrable_const _
  · exact Filter.Eventually.of_forall fun a ↦ by
      unfold gaussianKernel
      fun_prop

theorem measurable_gaussianMixture
    {d : ℕ} {Θ : Type*} [MeasurableSpace Θ]
    (μ : Measure Θ) [IsProbabilityMeasure μ]
    (θ : Θ → Point d) (hθ : Measurable θ) :
    Measurable (gaussianMixture μ θ) :=
  (continuous_gaussianMixture μ θ hθ).measurable

theorem integral_gaussianMixture
    {d : ℕ} {Θ : Type*} [MeasurableSpace Θ]
    (μ : Measure Θ) [IsProbabilityMeasure μ]
    (θ : Θ → Point d) (hθ : Measurable θ) :
    ∫ x : Point d, gaussianMixture μ θ x = 1 := by
  unfold gaussianMixture
  rw [← integral_integral_swap (gaussianKernel_comp_integrable_prod μ θ hθ)]
  simp_rw [integral_gaussianKernel]
  simp

theorem gaussianMixture_pos
    {d : ℕ} {Θ : Type*} [MeasurableSpace Θ]
    (μ : Measure Θ) [IsProbabilityMeasure μ]
    (θ : Θ → Point d) (hθ : Measurable θ) (x : Point d) :
    0 < gaussianMixture μ θ x := by
  unfold gaussianMixture
  let f : Θ → ℝ := fun a ↦
    Real.log (gaussianKernel d x (θ a))
  have hfint : Integrable (fun a ↦ Real.exp (f a)) μ := by
    apply (gaussianKernel_comp_integrable μ θ hθ x).congr
    exact Filter.Eventually.of_forall fun a ↦ by
      dsimp [f]
      rw [Real.exp_log (gaussianKernel_pos d x (θ a))]
  have hpos := integral_exp_pos hfint
  calc
    0 < ∫ a, Real.exp (f a) ∂μ := hpos
    _ = ∫ a, gaussianKernel d x (θ a) ∂μ := by
      apply integral_congr_ae
      exact Filter.Eventually.of_forall fun a ↦ by
        dsimp [f]
        rw [Real.exp_log (gaussianKernel_pos d x (θ a))]

theorem exp_inner_comp_integrable
    {d : ℕ} {Θ : Type*} [MeasurableSpace Θ]
    (μ : Measure Θ) [IsProbabilityMeasure μ]
    (θ : Θ → Point d) (hθmeas : Measurable θ)
    {S : ℝ} (hS : 0 ≤ S) (hθS : ∀ a, ‖θ a‖ ≤ S)
    (η : Point d) (hηS : ‖η‖ ≤ S) :
    Integrable (fun a ↦ Real.exp (inner ℝ (θ a) η)) μ := by
  apply Integrable.of_bound
    (by fun_prop : AEStronglyMeasurable
      (fun a ↦ Real.exp (inner ℝ (θ a) η)) μ)
    (Real.exp (S ^ 2))
  exact Filter.Eventually.of_forall fun a ↦ by
    rw [Real.norm_eq_abs, abs_of_pos (Real.exp_pos _)]
    apply Real.exp_le_exp.mpr
    calc
      inner ℝ (θ a) η ≤ |inner ℝ (θ a) η| := le_abs_self _
      _ ≤ ‖θ a‖ * ‖η‖ := abs_real_inner_le_norm _ _
      _ ≤ S * S := mul_le_mul (hθS a) hηS (norm_nonneg _) hS
      _ = S ^ 2 := by ring

theorem exp_inner_comp_comp_integrable
    {d : ℕ} {Θ : Type*} [MeasurableSpace Θ]
    (μ : Measure Θ) [IsProbabilityMeasure μ]
    (θ : Θ → Point d) (hθmeas : Measurable θ)
    {S : ℝ} (hS : 0 ≤ S) (hθS : ∀ a, ‖θ a‖ ≤ S) :
    Integrable (fun z : Θ × Θ ↦ Real.exp (inner ℝ (θ z.1) (θ z.2)))
      (μ.prod μ) := by
  apply Integrable.of_bound
    (by fun_prop : AEStronglyMeasurable
      (fun z : Θ × Θ ↦ Real.exp (inner ℝ (θ z.1) (θ z.2))) (μ.prod μ))
    (Real.exp (S ^ 2))
  exact Filter.Eventually.of_forall fun z ↦ by
    rw [Real.norm_eq_abs, abs_of_pos (Real.exp_pos _)]
    apply Real.exp_le_exp.mpr
    calc
      inner ℝ (θ z.1) (θ z.2) ≤
          |inner ℝ (θ z.1) (θ z.2)| := le_abs_self _
      _ ≤ ‖θ z.1‖ * ‖θ z.2‖ := abs_real_inner_le_norm _ _
      _ ≤ S * S := mul_le_mul (hθS z.1) (hθS z.2) (norm_nonneg _) hS
      _ = S ^ 2 := by ring

theorem gaussianKernel_product_div_density_comp_integrable_prod
    {d : ℕ} {Θ : Type*} [MeasurableSpace Θ]
    (μ : Measure Θ) [IsProbabilityMeasure μ]
    (θ : Θ → Point d) (hθmeas : Measurable θ)
    {S : ℝ} (hS : 0 ≤ S) (hθS : ∀ a, ‖θ a‖ ≤ S)
    (η : Point d) (hηS : ‖η‖ ≤ S) :
    Integrable (fun z : Θ × Point d ↦
      gaussianKernel d z.2 (θ z.1) * gaussianKernel d z.2 η /
        gaussianDensity d z.2) (μ.prod volume) := by
  have hmeas : AEStronglyMeasurable (fun z : Θ × Point d ↦
      gaussianKernel d z.2 (θ z.1) * gaussianKernel d z.2 η /
        gaussianDensity d z.2) (μ.prod volume) := by
    have hg : AEStronglyMeasurable (fun z : Θ × Point d ↦
        Real.exp (inner ℝ (θ z.1) η) *
          gaussianDensity d (z.2 - (θ z.1 + η))) (μ.prod volume) := by
      have hθfst : Measurable (fun z : Θ × Point d ↦ θ z.1) :=
        hθmeas.comp measurable_fst
      have hinner : Measurable (fun z : Θ × Point d ↦
          inner ℝ (θ z.1) η) :=
        continuous_inner.measurable.comp (hθfst.prodMk measurable_const)
      have hexp : Measurable (fun z : Θ × Point d ↦
          Real.exp (inner ℝ (θ z.1) η)) :=
        Real.continuous_exp.measurable.comp hinner
      have harg : Measurable (fun z : Θ × Point d ↦
          z.2 - (θ z.1 + η)) :=
        measurable_snd.sub (hθfst.add measurable_const)
      exact (hexp.mul ((continuous_gaussianDensity d).measurable.comp harg)).aestronglyMeasurable
    apply hg.congr
    exact Filter.Eventually.of_forall fun z ↦
      (gaussianKernel_product_div_density z.2 (θ z.1) η).symm
  rw [integrable_prod_iff hmeas]
  constructor
  · exact Filter.Eventually.of_forall fun a ↦
      gaussianKernel_product_div_density_integrable (θ a) η
  · have hfun : (fun a : Θ ↦ ∫ x : Point d,
        ‖gaussianKernel d x (θ a) * gaussianKernel d x η /
          gaussianDensity d x‖) =
        fun a ↦ Real.exp (inner ℝ (θ a) η) := by
      funext a
      have hpos : ∀ x : Point d,
          0 < gaussianKernel d x (θ a) * gaussianKernel d x η /
            gaussianDensity d x := fun x ↦
        div_pos (mul_pos (gaussianKernel_pos d x (θ a))
          (gaussianKernel_pos d x η)) (gaussianDensity_pos d x)
      simp_rw [Real.norm_eq_abs, abs_of_pos (hpos _)]
      exact integral_gaussianKernel_product_div_density (θ a) η
    rw [hfun]
    exact exp_inner_comp_integrable μ θ hθmeas hS hθS η hηS

theorem gaussianMixture_mul_kernel_div_density_integrable
    {d : ℕ} {Θ : Type*} [MeasurableSpace Θ]
    (μ : Measure Θ) [IsProbabilityMeasure μ]
    (θ : Θ → Point d) (hθmeas : Measurable θ)
    {S : ℝ} (hS : 0 ≤ S) (hθS : ∀ a, ‖θ a‖ ≤ S)
    (η : Point d) (hηS : ‖η‖ ≤ S) :
    Integrable (fun x : Point d ↦
      gaussianMixture μ θ x * gaussianKernel d x η / gaussianDensity d x) := by
  have hprod := gaussianKernel_product_div_density_comp_integrable_prod
    μ θ hθmeas hS hθS η hηS
  apply hprod.integral_prod_right.congr
  exact Filter.Eventually.of_forall fun x ↦ by
    unfold gaussianMixture
    change (∫ a, gaussianKernel d x (θ a) * gaussianKernel d x η /
        gaussianDensity d x ∂μ) =
      (∫ a, gaussianKernel d x (θ a) ∂μ) *
        gaussianKernel d x η / gaussianDensity d x
    symm
    rw [show (∫ a, gaussianKernel d x (θ a) ∂μ) *
        gaussianKernel d x η / gaussianDensity d x =
        (∫ a, gaussianKernel d x (θ a) ∂μ) *
          (gaussianKernel d x η / gaussianDensity d x) by ring]
    rw [← integral_mul_const]
    apply integral_congr_ae
    exact Filter.Eventually.of_forall fun a ↦ by ring

/-- Mixing the first argument of the Gaussian overlap identity commutes with
integration. -/
theorem integral_gaussianMixture_mul_kernel_div_density
    {d : ℕ} {Θ : Type*} [MeasurableSpace Θ]
    (μ : Measure Θ) [IsProbabilityMeasure μ]
    (θ : Θ → Point d) (hθmeas : Measurable θ)
    {S : ℝ} (hS : 0 ≤ S) (hθS : ∀ a, ‖θ a‖ ≤ S)
    (η : Point d) (hηS : ‖η‖ ≤ S) :
    ∫ x : Point d,
        gaussianMixture μ θ x * gaussianKernel d x η / gaussianDensity d x =
      ∫ a, Real.exp (inner ℝ (θ a) η) ∂μ := by
  have hprod := gaussianKernel_product_div_density_comp_integrable_prod
    μ θ hθmeas hS hθS η hηS
  unfold gaussianMixture
  calc
    (∫ x : Point d,
        (∫ a, gaussianKernel d x (θ a) ∂μ) * gaussianKernel d x η /
          gaussianDensity d x) =
        ∫ x : Point d, ∫ a,
          gaussianKernel d x (θ a) * gaussianKernel d x η /
            gaussianDensity d x ∂μ := by
      apply integral_congr_ae
      exact Filter.Eventually.of_forall fun x ↦ by
        change (∫ a, gaussianKernel d x (θ a) ∂μ) *
            gaussianKernel d x η / gaussianDensity d x =
          ∫ a, gaussianKernel d x (θ a) * gaussianKernel d x η /
            gaussianDensity d x ∂μ
        rw [show (∫ a, gaussianKernel d x (θ a) ∂μ) *
            gaussianKernel d x η / gaussianDensity d x =
            (∫ a, gaussianKernel d x (θ a) ∂μ) *
              (gaussianKernel d x η / gaussianDensity d x) by ring]
        rw [← integral_mul_const]
        apply integral_congr_ae
        exact Filter.Eventually.of_forall fun a ↦ by ring
    _ = ∫ a, ∫ x : Point d,
        gaussianKernel d x (θ a) * gaussianKernel d x η /
          gaussianDensity d x ∂volume ∂μ := by
      exact (integral_integral_swap hprod).symm
    _ = ∫ a, Real.exp (inner ℝ (θ a) η) ∂μ := by
      apply integral_congr_ae
      exact Filter.Eventually.of_forall fun a ↦
        integral_gaussianKernel_product_div_density (θ a) η

theorem gaussianMixture_sq_div_density_integrable_prod
    {d : ℕ} {Θ : Type*} [MeasurableSpace Θ]
    (μ : Measure Θ) [IsProbabilityMeasure μ]
    (θ : Θ → Point d) (hθmeas : Measurable θ)
    {S : ℝ} (hS : 0 ≤ S) (hθS : ∀ a, ‖θ a‖ ≤ S) :
    Integrable (fun z : Θ × Point d ↦
      gaussianMixture μ θ z.2 *
        Real.exp (gaussianScore z.2 (θ z.1))) (μ.prod volume) := by
  have hp := gaussianMixture_integrable μ θ hθmeas
  have hscore : Measurable (fun z : Θ × Point d ↦
      Real.exp (gaussianScore z.2 (θ z.1))) :=
    Real.continuous_exp.measurable.comp
      ((continuous_gaussianScore d).measurable.comp
        (measurable_snd.prodMk (hθmeas.comp measurable_fst)))
  have hmeas : AEStronglyMeasurable (fun z : Θ × Point d ↦
      gaussianMixture μ θ z.2 *
        Real.exp (gaussianScore z.2 (θ z.1))) (μ.prod volume) :=
    hp.aestronglyMeasurable.comp_snd.mul hscore.aestronglyMeasurable
  rw [integrable_prod_iff hmeas]
  constructor
  · exact Filter.Eventually.of_forall fun a ↦ by
      apply (gaussianMixture_mul_kernel_div_density_integrable
        μ θ hθmeas hS hθS (θ a) (hθS a)).congr
      exact Filter.Eventually.of_forall fun x ↦ by
        change gaussianMixture μ θ x * gaussianKernel d x (θ a) /
            gaussianDensity d x =
          gaussianMixture μ θ x * Real.exp (gaussianScore x (θ a))
        rw [gaussianKernel_eq_density_mul_exp_score]
        field_simp [(gaussianDensity_pos d x).ne']
  · have hdouble := exp_inner_comp_comp_integrable μ θ hθmeas hS hθS
    apply hdouble.integral_prod_right.congr
    exact Filter.Eventually.of_forall fun a ↦ by
      change (∫ b, Real.exp (inner ℝ (θ b) (θ a)) ∂μ) =
        ∫ x : Point d,
          ‖gaussianMixture μ θ x * Real.exp (gaussianScore x (θ a))‖
      symm
      rw [show (∫ x : Point d,
          ‖gaussianMixture μ θ x * Real.exp (gaussianScore x (θ a))‖) =
          ∫ x : Point d,
            gaussianMixture μ θ x * gaussianKernel d x (θ a) /
              gaussianDensity d x by
        apply integral_congr_ae
        exact Filter.Eventually.of_forall fun x ↦ by
          change ‖gaussianMixture μ θ x * Real.exp (gaussianScore x (θ a))‖ =
            gaussianMixture μ θ x * gaussianKernel d x (θ a) /
              gaussianDensity d x
          rw [Real.norm_eq_abs, abs_of_pos (mul_pos
            (gaussianMixture_pos μ θ hθmeas x) (Real.exp_pos _)),
            gaussianKernel_eq_density_mul_exp_score]
          field_simp [(gaussianDensity_pos d x).ne']]
      exact integral_gaussianMixture_mul_kernel_div_density
        μ θ hθmeas hS hθS (θ a) (hθS a)

theorem gaussianMixture_sq_div_density_integrable
    {d : ℕ} {Θ : Type*} [MeasurableSpace Θ]
    (μ : Measure Θ) [IsProbabilityMeasure μ]
    (θ : Θ → Point d) (hθmeas : Measurable θ)
    {S : ℝ} (hS : 0 ≤ S) (hθS : ∀ a, ‖θ a‖ ≤ S) :
    Integrable (fun x : Point d ↦
      (gaussianMixture μ θ x) ^ 2 / gaussianDensity d x) := by
  have hprod := gaussianMixture_sq_div_density_integrable_prod
    μ θ hθmeas hS hθS
  apply hprod.integral_prod_right.congr
  exact Filter.Eventually.of_forall fun x ↦ by
    change (∫ a, gaussianMixture μ θ x *
        Real.exp (gaussianScore x (θ a)) ∂μ) =
      (gaussianMixture μ θ x) ^ 2 / gaussianDensity d x
    symm
    have hmix : gaussianMixture μ θ x = gaussianDensity d x *
        ∫ a, Real.exp (gaussianScore x (θ a)) ∂μ := by
      unfold gaussianMixture
      simp_rw [gaussianKernel_eq_density_mul_exp_score]
      exact integral_const_mul _ _
    rw [integral_const_mul, hmix]
    field_simp [(gaussianDensity_pos d x).ne']

theorem integral_gaussianMixture_sq_div_density
    {d : ℕ} {Θ : Type*} [MeasurableSpace Θ]
    (μ : Measure Θ) [IsProbabilityMeasure μ]
    (θ : Θ → Point d) (hθmeas : Measurable θ)
    {S : ℝ} (hS : 0 ≤ S) (hθS : ∀ a, ‖θ a‖ ≤ S) :
    ∫ x : Point d, (gaussianMixture μ θ x) ^ 2 / gaussianDensity d x =
      ∫ a, ∫ b, Real.exp (inner ℝ (θ b) (θ a)) ∂μ ∂μ := by
  have hprod := gaussianMixture_sq_div_density_integrable_prod
    μ θ hθmeas hS hθS
  calc
    (∫ x : Point d, (gaussianMixture μ θ x) ^ 2 / gaussianDensity d x) =
        ∫ x : Point d, ∫ a,
          gaussianMixture μ θ x * Real.exp (gaussianScore x (θ a)) ∂μ := by
      apply integral_congr_ae
      exact Filter.Eventually.of_forall fun x ↦ by
        change (gaussianMixture μ θ x) ^ 2 / gaussianDensity d x =
          ∫ a, gaussianMixture μ θ x * Real.exp (gaussianScore x (θ a)) ∂μ
        have hmix : gaussianMixture μ θ x = gaussianDensity d x *
            ∫ a, Real.exp (gaussianScore x (θ a)) ∂μ := by
          unfold gaussianMixture
          simp_rw [gaussianKernel_eq_density_mul_exp_score]
          exact integral_const_mul _ _
        rw [integral_const_mul, hmix]
        field_simp [(gaussianDensity_pos d x).ne']
    _ = ∫ a, ∫ x : Point d,
        gaussianMixture μ θ x * Real.exp (gaussianScore x (θ a)) ∂volume ∂μ := by
      exact (integral_integral_swap hprod).symm
    _ = ∫ a, ∫ b, Real.exp (inner ℝ (θ b) (θ a)) ∂μ ∂μ := by
      apply integral_congr_ae
      exact Filter.Eventually.of_forall fun a ↦ by
        change (∫ x : Point d,
            gaussianMixture μ θ x * Real.exp (gaussianScore x (θ a))) =
          ∫ b, Real.exp (inner ℝ (θ b) (θ a)) ∂μ
        rw [show (∫ x : Point d,
            gaussianMixture μ θ x * Real.exp (gaussianScore x (θ a))) =
            ∫ x : Point d,
              gaussianMixture μ θ x * gaussianKernel d x (θ a) /
                gaussianDensity d x by
          apply integral_congr_ae
          exact Filter.Eventually.of_forall fun x ↦ by
            change gaussianMixture μ θ x * Real.exp (gaussianScore x (θ a)) =
              gaussianMixture μ θ x * gaussianKernel d x (θ a) /
                gaussianDensity d x
            rw [gaussianKernel_eq_density_mul_exp_score]
            field_simp [(gaussianDensity_pos d x).ne']]
        exact integral_gaussianMixture_mul_kernel_div_density
          μ θ hθmeas hS hθS (θ a) (hθS a)

end ReweightedNPMLE
