import ReweightedNPMLE.DirichletDistribution
import ReweightedNPMLE.DirichletIndependence
import ReweightedNPMLE.DirichletSecondMoment
import ReweightedNPMLE.EmpiricalDirichletTV
import ReweightedNPMLE.FittedEnvelope
import ReweightedNPMLE.FullEffectiveDimension
import ReweightedNPMLE.FullExtremeSupport
import ReweightedNPMLE.FullSupportSensitivity
import ReweightedNPMLE.GammaDistribution
import ReweightedNPMLE.GaussianApproxTheorem
import ReweightedNPMLE.GaussianConditionalTheorem
import ReweightedNPMLE.GaussianGenericity
import ReweightedNPMLE.GaussianJointConsistency
import ReweightedNPMLE.GaussianMainTheorem
import ReweightedNPMLE.GaussianNearMLETheorem
import ReweightedNPMLE.GaussianPaperFiniteNet
import ReweightedNPMLE.GaussianProbabilityWidth
import ReweightedNPMLE.GaussianSupportRefinements
import ReweightedNPMLE.GaussianTinyJoint
import ReweightedNPMLE.MeasureExtremeSupport
import ReweightedNPMLE.PaperLocalization
import ReweightedNPMLE.PaperRegularity
import ReweightedNPMLE.PopulationCriterion
import ReweightedNPMLE.PopulationKL
import ReweightedNPMLE.ProbabilityOptimizerFiber

/-! Release interface type and axiom inventory. This scratch audit does not change production Lean. -/

set_option format.width 120
set_option pp.funBinderTypes true
set_option pp.piBinderTypes true

#check @ReweightedNPMLE.gammaWeight_normalize_total_joint_law
#check @ReweightedNPMLE.gammaWeight_normalize_indep_total
#check @ReweightedNPMLE.symmetricDirichlet_weighted_empirical_mean
#check @ReweightedNPMLE.symmetricDirichlet_weighted_empirical_variance
#check @ReweightedNPMLE.empiricalDirichlet_expected_tv_le
#check @ReweightedNPMLE.empiricalDirichletTV_eq_half_sum_actual_atom_mass_differences
#check @ReweightedNPMLE.compactGaussianMixture_unchanged_population_criterion
#check @ReweightedNPMLE.compactGaussianMixture_population_gap_eq_klDiv
#check @ReweightedNPMLE.gaussian_exact_regularization_main
#check @ReweightedNPMLE.gaussian_main_support_dimension_refinements
#check @ReweightedNPMLE.gaussian_exact_regularization_joint_tiny_explicit
#check @ReweightedNPMLE.gaussian_exact_regularization_tiny
#check @ReweightedNPMLE.gaussian_reweighted_optimizer_weak_consistency
#check @ReweightedNPMLE.effective_dimension_full_support
#check @ReweightedNPMLE.full_support_sensitivity_ae
#check @ReweightedNPMLE.gaussian_probability_relative_width_bound
#check @ReweightedNPMLE.gaussianTaylorResidual_eq_zero_of_mul_eq_zero
#check @ReweightedNPMLE.gaussian_conditional_structural_and_likelihood_bounds
#check @ReweightedNPMLE.gaussian_generic_evaluation_independence
#check @ReweightedNPMLE.gaussian_generic_optimizer_fiber_uniqueness
#check @ReweightedNPMLE.gaussian_uniform_nearMLE_paper_theorem
#check @ReweightedNPMLE.gaussian_approximate_optimizer_joint_robustness
#check @ReweightedNPMLE.positive_kernel_hull_properties
#check @ReweightedNPMLE.canonical_fitted_value_convexOn_univ
#check @ReweightedNPMLE.canonical_fitted_maps_locally_lipschitz
#check @ReweightedNPMLE.canonical_fitted_value_contDiffOn_one
#check @ReweightedNPMLE.paper_full_optimizer_fiber_geometry
#check @ReweightedNPMLE.canonicalFittedOptimalValue_hasFDerivAt_of_positive_weights
#check @ReweightedNPMLE.full_probability_optimizer_extreme_iff
#check @ReweightedNPMLE.full_extreme_optimizer_support_finite_card_le
#check @ReweightedNPMLE.measurable_maximumExtremeSupport
#check @ReweightedNPMLE.canonical_maximumExtremeSupport_attained
#check @ReweightedNPMLE.full_extreme_optimizer_hessian_projection
#check @ReweightedNPMLE.isCompact_paperRadialEvent
#check @ReweightedNPMLE.paper_radial_localization
#check @ReweightedNPMLE.canonical_paper_radial_exact_fit
#check @ReweightedNPMLE.canonical_maximumExtremeSupport_paper_gamma_moment
#check @ReweightedNPMLE.compactGaussianMixture_simultaneous_paper_finite_net
#check @ReweightedNPMLE.gamma_coordinate_concentration
#check @ReweightedNPMLE.probability_optimizer_exists

#print axioms ReweightedNPMLE.gammaWeight_normalize_total_joint_law
#print axioms ReweightedNPMLE.gammaWeight_normalize_indep_total
#print axioms ReweightedNPMLE.symmetricDirichlet_weighted_empirical_mean
#print axioms ReweightedNPMLE.symmetricDirichlet_weighted_empirical_variance
#print axioms ReweightedNPMLE.empiricalDirichlet_expected_tv_le
#print axioms ReweightedNPMLE.empiricalDirichletTV_eq_half_sum_actual_atom_mass_differences
#print axioms ReweightedNPMLE.compactGaussianMixture_unchanged_population_criterion
#print axioms ReweightedNPMLE.compactGaussianMixture_population_gap_eq_klDiv
#print axioms ReweightedNPMLE.gaussian_exact_regularization_main
#print axioms ReweightedNPMLE.gaussian_main_support_dimension_refinements
#print axioms ReweightedNPMLE.gaussian_exact_regularization_joint_tiny_explicit
#print axioms ReweightedNPMLE.gaussian_exact_regularization_tiny
#print axioms ReweightedNPMLE.gaussian_reweighted_optimizer_weak_consistency
#print axioms ReweightedNPMLE.effective_dimension_full_support
#print axioms ReweightedNPMLE.full_support_sensitivity_ae
#print axioms ReweightedNPMLE.gaussian_probability_relative_width_bound
#print axioms ReweightedNPMLE.gaussianTaylorResidual_eq_zero_of_mul_eq_zero
#print axioms ReweightedNPMLE.gaussian_conditional_structural_and_likelihood_bounds
#print axioms ReweightedNPMLE.gaussian_generic_evaluation_independence
#print axioms ReweightedNPMLE.gaussian_generic_optimizer_fiber_uniqueness
#print axioms ReweightedNPMLE.gaussian_uniform_nearMLE_paper_theorem
#print axioms ReweightedNPMLE.gaussian_approximate_optimizer_joint_robustness
#print axioms ReweightedNPMLE.positive_kernel_hull_properties
#print axioms ReweightedNPMLE.canonical_fitted_value_convexOn_univ
#print axioms ReweightedNPMLE.canonical_fitted_maps_locally_lipschitz
#print axioms ReweightedNPMLE.canonical_fitted_value_contDiffOn_one
#print axioms ReweightedNPMLE.paper_full_optimizer_fiber_geometry
#print axioms ReweightedNPMLE.canonicalFittedOptimalValue_hasFDerivAt_of_positive_weights
#print axioms ReweightedNPMLE.full_probability_optimizer_extreme_iff
#print axioms ReweightedNPMLE.full_extreme_optimizer_support_finite_card_le
#print axioms ReweightedNPMLE.measurable_maximumExtremeSupport
#print axioms ReweightedNPMLE.canonical_maximumExtremeSupport_attained
#print axioms ReweightedNPMLE.full_extreme_optimizer_hessian_projection
#print axioms ReweightedNPMLE.isCompact_paperRadialEvent
#print axioms ReweightedNPMLE.paper_radial_localization
#print axioms ReweightedNPMLE.canonical_paper_radial_exact_fit
#print axioms ReweightedNPMLE.canonical_maximumExtremeSupport_paper_gamma_moment
#print axioms ReweightedNPMLE.compactGaussianMixture_simultaneous_paper_finite_net
#print axioms ReweightedNPMLE.gamma_coordinate_concentration
#print axioms ReweightedNPMLE.probability_optimizer_exists
